version: '3.4'

services:
  eventsourcingexample.api:
    image: ${DOCKER_REGISTRY-}eventsourcingexampleapi
    build:
      context: .
      dockerfile: EventSourcingExample.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "eventstoredb"
      - "readdb"

  eventstoredb:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=True
    ports:
      - "2113:2113"
  readdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"  
    ports: 
      - "1435:1433"